apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Farm Animals</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; }
            h1 { color: #4CAF50; }
            ul { list-style-type: none; padding: 0; }
            li { 
                margin: 20px 0; 
                font-size: 20px; 
                display: flex; 
                align-items: center; 
                justify-content: center; 
            }
            img { 
                width: 50px; 
                height: 50px; 
                margin-right: 10px; 
                object-fit: cover; 
            }
        </style>
    </head>
    <body>
        <h1>6 Farm Animals</h1>
        <ul>
            <li><img src="https://raw.githubusercontent.com/wailwinphone/web-server-demo/master/images/cow.jpg" alt="Cow">Cow</li>
            <li><img src="https://raw.githubusercontent.com/wailwinphone/web-server-demo/master/images/sheep.jpeg" alt="Sheep">Sheep</li>
            <li><img src="/usr/share/nginx/html/images/pig.jpg" alt="Pig">Pig</li>
            <li><img src="/home/wlp/web-server-demo/images/chicken.jpeg" alt="Chicken">Chick</li>
            <li><img src="images/horse.jpeg" alt="Horse">Horse</li>
            <li><img src="goat.jpg" alt="Goat">Donkey</li>
        </ul>
    </body>
    </html>