apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Farm Animals</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; }
            h1 { color: #4CAF50; }
            ul { list-style-type: none; padding: 0; }
            li { margin: 10px 0; font-size: 20px; }
        </style>
    </head>
    <body>
        <h1>6 Wild Animals</h1>
        <ul>
            <li>Lion</li>
            <li>Tiger</li>
            <li>Pig</li>
            <li>Chicken</li>
            <li>Horse</li>
            <li>Goat</li>
        </ul>
    </body>
    </html>