apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/wlp/web-server-demo/images
    type: Directory
